version: '2'
services:
  web:
    build: .
    ports:
      - 80:80
    links:
      # - account
      - event_log
    entrypoint: ./web
  # account:
  #   build: .
  #   command: ["./account"]
  event_log:
    build: .
    entrypoint: ./event_log
    volumes:
       - ./data:/data
