version: '2'
services:
  web:
    build: .
    ports:
      - 80:80
    links:
      - account
      - event_log
    command: ["./web"]
  account:
    build: .
    command: ["./account"]
  event_log:
    build: .
    command: ["./event_log"]
    volumes:
       - ./data:/data
